from __future__ import annotations

# Danh mục đơn vị hành chính cấp tỉnh có hiệu lực từ ngày 01/07/2025.
CURRENT_PROVINCES: tuple[str, ...] = (
    "An Giang",
    "Bắc Ninh",
    "Cao Bằng",
    "Cà Mau",
    "Cần Thơ",
    "Điện Biên",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Phòng",
    "Huế",
    "Hưng Yên",
    "Khánh Hòa",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Nghệ An",
    "Ninh Bình",
    "Phú Thọ",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sơn La",
    "Thanh Hóa",
    "Thái Nguyên",
    "Thành phố Hồ Chí Minh",
    "Tuyên Quang",
    "Tây Ninh",
    "Vĩnh Long",
)


# Giữ khả năng đọc dữ liệu cũ nhưng luôn trả về tên tỉnh/thành hiện hành.
CURRENT_PROVINCE_BY_LEGACY_NAME: dict[str, str] = {
    "An Giang": "An Giang",
    "Bà Rịa - Vũng Tàu": "Thành phố Hồ Chí Minh",
    "Bình Dương": "Thành phố Hồ Chí Minh",
    "Bình Phước": "Đồng Nai",
    "Bình Thuận": "Lâm Đồng",
    "Bình Định": "Gia Lai",
    "Bạc Liêu": "Cà Mau",
    "Bắc Giang": "Bắc Ninh",
    "Bắc Kạn": "Thái Nguyên",
    "Bắc Ninh": "Bắc Ninh",
    "Bến Tre": "Vĩnh Long",
    "Cao Bằng": "Cao Bằng",
    "Cà Mau": "Cà Mau",
    "Cần Thơ": "Cần Thơ",
    "Gia Lai": "Gia Lai",
    "Hà Giang": "Tuyên Quang",
    "Hà Nam": "Ninh Bình",
    "Hà Nội": "Hà Nội",
    "Hà Tĩnh": "Hà Tĩnh",
    "Hòa Bình": "Phú Thọ",
    "Hưng Yên": "Hưng Yên",
    "Hải Dương": "Hải Phòng",
    "Hải Phòng": "Hải Phòng",
    "Hậu Giang": "Cần Thơ",
    "Huế": "Huế",
    "Khánh Hòa": "Khánh Hòa",
    "Kiên Giang": "An Giang",
    "Kon Tum": "Quảng Ngãi",
    "Lai Châu": "Lai Châu",
    "Long An": "Tây Ninh",
    "Lào Cai": "Lào Cai",
    "Lâm Đồng": "Lâm Đồng",
    "Lạng Sơn": "Lạng Sơn",
    "Nam Định": "Ninh Bình",
    "Nghệ An": "Nghệ An",
    "Ninh Bình": "Ninh Bình",
    "Ninh Thuận": "Khánh Hòa",
    "Phú Thọ": "Phú Thọ",
    "Phú Yên": "Đắk Lắk",
    "Quảng Bình": "Quảng Trị",
    "Quảng Nam": "Đà Nẵng",
    "Quảng Ngãi": "Quảng Ngãi",
    "Quảng Ninh": "Quảng Ninh",
    "Quảng Trị": "Quảng Trị",
    "Sóc Trăng": "Cần Thơ",
    "Sơn La": "Sơn La",
    "Thanh Hóa": "Thanh Hóa",
    "Thành phố Hồ Chí Minh": "Thành phố Hồ Chí Minh",
    "Thái Bình": "Hưng Yên",
    "Thái Nguyên": "Thái Nguyên",
    "Thừa Thiên Huế": "Huế",
    "Tiền Giang": "Đồng Tháp",
    "Trà Vinh": "Vĩnh Long",
    "Tuyên Quang": "Tuyên Quang",
    "Tây Ninh": "Tây Ninh",
    "Vĩnh Long": "Vĩnh Long",
    "Vĩnh Phúc": "Phú Thọ",
    "Yên Bái": "Lào Cai",
    "Điện Biên": "Điện Biên",
    "Đà Nẵng": "Đà Nẵng",
    "Đắk Lắk": "Đắk Lắk",
    "Đắk Nông": "Lâm Đồng",
    "Đồng Nai": "Đồng Nai",
    "Đồng Tháp": "Đồng Tháp",
}


def normalize_province_name(name: str) -> str:
    normalized = name.strip()
    return CURRENT_PROVINCE_BY_LEGACY_NAME.get(normalized, normalized)
