from __future__ import annotations

from .geography import normalize_province_name
from .models import Coordinate, Place, TicketOffer

PLACES: list[Place] = [
    Place(
        id="ha-long-bay",
        name="Vịnh Hạ Long",
        region="north",
        province="Quảng Ninh",
        categories=["beach", "island", "culture"],
        description="Kỳ quan thiên nhiên thế giới nổi bật với hàng nghìn đảo đá vôi, hang động và trải nghiệm du thuyền nghỉ dưỡng.",
        highlights=["Du thuyền ngủ đêm", "Chèo kayak", "Hang Sửng Sốt"],
        ticket_price=320000,
        avg_spend=1800000,
        rating=4.9,
        must_go_score=98,
        coordinate=Coordinate(lat=20.9101, lng=107.1839),
        nearby_services=["hotel", "pharmacy", "supermarket", "hospital"],
        transport_modes=["plane", "bus", "car"],
        image_hint="sunrise bay cruise",
    ),
    Place(
        id="sapa",
        name="Sa Pa",
        region="north",
        province="Lào Cai",
        categories=["mountain", "culture", "food"],
        description="Thị trấn vùng cao nổi tiếng với ruộng bậc thang, đỉnh Fansipan và trải nghiệm văn hóa bản địa.",
        highlights=["Fansipan Legend", "Bản Cát Cát", "Ruộng bậc thang"],
        ticket_price=250000,
        avg_spend=1500000,
        rating=4.8,
        must_go_score=95,
        coordinate=Coordinate(lat=22.3364, lng=103.8438),
        nearby_services=["hotel", "drugstore", "market", "cafe"],
        transport_modes=["train", "bus", "car"],
        image_hint="mountain terraces clouds",
    ),
    Place(
        id="trang-an",
        name="Tràng An",
        region="north",
        province="Ninh Bình",
        categories=["spiritual", "culture", "history"],
        description="Quần thể danh thắng kết hợp sông núi, hang động và những điểm đến tâm linh đặc sắc của miền Bắc.",
        highlights=["Đi thuyền Tràng An", "Chùa Bái Đính", "Hang Múa"],
        ticket_price=250000,
        avg_spend=1200000,
        rating=4.7,
        must_go_score=92,
        coordinate=Coordinate(lat=20.2506, lng=105.9745),
        nearby_services=["homestay", "market", "hospital", "pharmacy"],
        transport_modes=["bus", "car", "train"],
        image_hint="river mountain temple",
    ),
    Place(
        id="hue-imperial-city",
        name="Cố đô Huế",
        region="central",
        province="Thừa Thiên Huế",
        categories=["history", "culture", "spiritual"],
        description="Không gian di sản cố đô kết hợp cung đình, ẩm thực Huế và quần thể lăng tẩm triều Nguyễn.",
        highlights=["Đại Nội", "Lăng Khải Định", "Chùa Thiên Mụ"],
        ticket_price=200000,
        avg_spend=1300000,
        rating=4.7,
        must_go_score=94,
        coordinate=Coordinate(lat=16.4637, lng=107.5909),
        nearby_services=["hotel", "pharmacy", "hospital", "night-market"],
        transport_modes=["plane", "train", "bus"],
        image_hint="imperial citadel dawn",
    ),
    Place(
        id="hoi-an",
        name="Phố cổ Hội An",
        region="central",
        province="Quảng Nam",
        categories=["culture", "food", "history"],
        description="Đô thị cổ bên sông Hoài với đèn lồng, nhà cổ, may đo nhanh và không khí du lịch nhẹ nhàng.",
        highlights=["Phố đèn lồng", "Chùa Cầu", "May đo lấy nhanh"],
        ticket_price=120000,
        avg_spend=1400000,
        rating=4.8,
        must_go_score=97,
        coordinate=Coordinate(lat=15.8801, lng=108.3380),
        nearby_services=["tailor", "hotel", "pharmacy", "convenience-store"],
        transport_modes=["plane", "train", "car"],
        image_hint="lantern old town sunset",
    ),
    Place(
        id="ba-na-hills",
        name="Bà Nà Hills",
        region="central",
        province="Đà Nẵng",
        categories=["mountain", "entertainment", "culture"],
        description="Khu du lịch trên núi nổi bật với Cầu Vàng, cáp treo, làng Pháp và công viên giải trí trong sương mây.",
        highlights=["Cầu Vàng", "French Village", "Fantasy Park"],
        ticket_price=900000,
        avg_spend=2000000,
        rating=4.6,
        must_go_score=90,
        coordinate=Coordinate(lat=15.9950, lng=107.9967),
        nearby_services=["theme-park", "hotel", "restaurant", "first-aid"],
        transport_modes=["plane", "bus", "car"],
        image_hint="golden bridge mountain",
    ),
    Place(
        id="phu-quoc",
        name="Phú Quốc",
        region="south",
        province="Kiên Giang",
        categories=["island", "beach", "food"],
        description="Đảo ngọc phía Nam với biển xanh, bãi cát dài, chợ đêm và nhiều khu nghỉ dưỡng cao cấp.",
        highlights=["Bãi Sao", "Sunset Town", "Hòn Thơm"],
        ticket_price=600000,
        avg_spend=2400000,
        rating=4.9,
        must_go_score=99,
        coordinate=Coordinate(lat=10.2899, lng=103.9840),
        nearby_services=["resort", "pharmacy", "supermarket", "hospital"],
        transport_modes=["plane", "ship"],
        image_hint="island beach tropical",
    ),
    Place(
        id="can-tho",
        name="Cần Thơ",
        region="south",
        province="Cần Thơ",
        categories=["culture", "food", "history"],
        description="Thành phố trung tâm miền Tây nổi bật với chợ nổi, bến Ninh Kiều và nhịp sống sông nước hiền hòa.",
        highlights=["Chợ nổi Cái Răng", "Bến Ninh Kiều", "Nhà cổ Bình Thủy"],
        ticket_price=100000,
        avg_spend=1100000,
        rating=4.6,
        must_go_score=89,
        coordinate=Coordinate(lat=10.0452, lng=105.7469),
        nearby_services=["hotel", "market", "pharmacy", "hospital"],
        transport_modes=["plane", "bus", "car"],
        image_hint="floating market sunrise",
    ),
    Place(
        id="ho-chi-minh-city",
        name="Thành phố Hồ Chí Minh",
        region="south",
        province="Thành phố Hồ Chí Minh",
        categories=["culture", "food", "entertainment", "history"],
        description="Đô thị năng động bậc nhất Việt Nam với điểm tham quan lịch sử, mua sắm, ẩm thực và đời sống đêm sôi động.",
        highlights=["Dinh Độc Lập", "Chợ Bến Thành", "Phố đi bộ Nguyễn Huệ"],
        ticket_price=0,
        avg_spend=1600000,
        rating=4.7,
        must_go_score=93,
        coordinate=Coordinate(lat=10.8231, lng=106.6297),
        nearby_services=["hotel", "hospital", "supermarket", "pharmacy"],
        transport_modes=["plane", "train", "bus"],
        image_hint="skyline city evening",
    ),
]


def _province_place(
    place_id: str,
    name: str,
    region: str,
    province: str,
    categories: list[str],
    description: str,
    highlights: list[str],
    lat: float,
    lng: float,
    ticket_price: float = 80000,
    avg_spend: float = 900000,
    rating: float = 4.5,
    must_go_score: int = 82,
    transport_modes: list[str] | None = None,
    nearby_services: list[str] | None = None,
    image_hint: str = "vietnam destination",
) -> Place:
    return Place(
        id=place_id,
        name=name,
        region=region,
        province=province,
        categories=categories,
        description=description,
        highlights=highlights,
        ticket_price=ticket_price,
        avg_spend=avg_spend,
        rating=rating,
        must_go_score=must_go_score,
        coordinate=Coordinate(lat=lat, lng=lng),
        nearby_services=nearby_services or ["hotel", "restaurant", "pharmacy", "market"],
        transport_modes=transport_modes or ["bus", "car"],
        image_hint=image_hint,
    )


PLACES.extend(
    [
        _province_place(
            "ha-noi-old-quarter",
            "Phố cổ Hà Nội",
            "north",
            "Hà Nội",
            ["culture", "history", "food"],
            "Khu phố cổ trung tâm Thủ đô với di sản kiến trúc, hồ Hoàn Kiếm, ẩm thực đường phố và nhịp sống đô thị đặc trưng.",
            ["Hồ Hoàn Kiếm", "Phố cổ", "Ẩm thực Hà Nội"],
            21.0285,
            105.8542,
            ticket_price=0,
            avg_spend=1200000,
            rating=4.8,
            must_go_score=96,
            transport_modes=["plane", "train", "bus", "car"],
            image_hint="hanoi old quarter lake",
        ),
        _province_place(
            "cat-ba",
            "Đảo Cát Bà",
            "north",
            "Hải Phòng",
            ["island", "beach", "culture"],
            "Quần đảo Cát Bà nổi bật với vịnh Lan Hạ, rừng quốc gia, bãi biển và các tuyến chèo kayak trên biển.",
            ["Vịnh Lan Hạ", "Rừng quốc gia Cát Bà", "Chèo kayak"],
            20.7278,
            107.0482,
            ticket_price=120000,
            avg_spend=1500000,
            rating=4.7,
            must_go_score=92,
            transport_modes=["bus", "ship", "car"],
            image_hint="cat ba island lan ha bay",
        ),
        _province_place(
            "bac-ninh-dong-ho",
            "Làng tranh Đông Hồ",
            "north",
            "Bắc Ninh",
            ["culture", "history"],
            "Làng nghề tranh dân gian nổi tiếng, phù hợp trải nghiệm văn hóa Kinh Bắc và tìm hiểu nghệ thuật thủ công truyền thống.",
            ["Tranh Đông Hồ", "Dân ca quan họ", "Làng nghề"],
            21.0980,
            106.0730,
            50000,
            650000,
            4.4,
            78,
            image_hint="dong ho folk painting village",
        ),
        _province_place(
            "tam-chuc",
            "Chùa Tam Chúc",
            "north",
            "Hà Nam",
            ["spiritual", "culture"],
            "Quần thể du lịch tâm linh lớn bên hồ Tam Chúc, kết hợp cảnh quan núi đá vôi và không gian hành hương.",
            ["Chùa Tam Chúc", "Hồ Tam Chúc", "Điện Tam Thế"],
            20.5712,
            105.9220,
            120000,
            750000,
            4.5,
            83,
            image_hint="tam chuc pagoda lake",
        ),
        _province_place(
            "con-son-kiep-bac",
            "Côn Sơn - Kiếp Bạc",
            "north",
            "Hải Dương",
            ["spiritual", "history", "culture"],
            "Khu di tích gắn với Trần Hưng Đạo và Nguyễn Trãi, phù hợp hành trình lịch sử và tâm linh miền Bắc.",
            ["Đền Kiếp Bạc", "Chùa Côn Sơn", "Suối Côn Sơn"],
            21.1343,
            106.3980,
            40000,
            700000,
            4.4,
            80,
            image_hint="con son kiep bac temple",
        ),
        _province_place(
            "pho-hien",
            "Phố Hiến",
            "north",
            "Hưng Yên",
            ["history", "culture", "food"],
            "Không gian thương cảng xưa bên sông Hồng với chùa cổ, đền miếu và đặc sản nhãn lồng Hưng Yên.",
            ["Văn Miếu Xích Đằng", "Đền Mẫu", "Nhãn lồng"],
            20.6464,
            106.0511,
            30000,
            650000,
            4.3,
            77,
            image_hint="pho hien old town temple",
        ),
        _province_place(
            "tran-temple-nam-dinh",
            "Đền Trần Nam Định",
            "north",
            "Nam Định",
            ["spiritual", "history", "culture"],
            "Quần thể đền Trần là điểm hành hương nổi bật, gắn với lịch sử nhà Trần và lễ khai ấn đầu xuân.",
            ["Đền Trần", "Phủ Dầy", "Lễ khai ấn"],
            20.4388,
            106.1621,
            30000,
            650000,
            4.4,
            81,
            image_hint="tran temple nam dinh",
        ),
        _province_place(
            "con-den",
            "Biển Cồn Đen",
            "north",
            "Thái Bình",
            ["beach", "food"],
            "Điểm du lịch sinh thái ven biển với rừng ngập mặn, bãi cát và hải sản địa phương.",
            ["Rừng ngập mặn", "Bãi biển Cồn Đen", "Hải sản"],
            20.3387,
            106.5790,
            50000,
            750000,
            4.2,
            75,
            image_hint="con den beach mangrove",
        ),
        _province_place(
            "tam-dao",
            "Tam Đảo",
            "north",
            "Vĩnh Phúc",
            ["mountain", "food", "culture"],
            "Thị trấn nghỉ dưỡng trên núi có khí hậu mát mẻ, nhà thờ đá, thác Bạc và nhiều quán cà phê săn mây.",
            ["Nhà thờ đá", "Thác Bạc", "Săn mây"],
            21.4569,
            105.6465,
            80000,
            1000000,
            4.5,
            86,
            image_hint="tam dao mountain town",
        ),
        _province_place(
            "hung-temple",
            "Đền Hùng",
            "north",
            "Phú Thọ",
            ["spiritual", "history", "culture"],
            "Khu di tích quốc gia đặc biệt thờ các Vua Hùng, điểm đến quan trọng trong hành trình về cội nguồn.",
            ["Đền Hùng", "Giỗ Tổ Hùng Vương", "Núi Nghĩa Lĩnh"],
            21.3709,
            105.3182,
            20000,
            700000,
            4.7,
            90,
            image_hint="hung kings temple",
        ),
        _province_place(
            "tan-trao",
            "Tân Trào",
            "north",
            "Tuyên Quang",
            ["history", "culture", "mountain"],
            "Khu di tích cách mạng trong không gian núi rừng Việt Bắc, phù hợp du lịch lịch sử và giáo dục truyền thống.",
            ["Đình Tân Trào", "Cây đa Tân Trào", "Lán Nà Nưa"],
            21.7811,
            105.4606,
            30000,
            800000,
            4.4,
            82,
            image_hint="tan trao historic forest",
        ),
        _province_place(
            "dong-van",
            "Cao nguyên đá Đồng Văn",
            "north",
            "Hà Giang",
            ["mountain", "culture"],
            "Cung đường núi đá hùng vĩ với đèo Mã Pí Lèng, sông Nho Quế và văn hóa các dân tộc vùng cao.",
            ["Đèo Mã Pí Lèng", "Sông Nho Quế", "Phố cổ Đồng Văn"],
            23.2787,
            105.3622,
            100000,
            1600000,
            4.9,
            97,
            image_hint="dong van karst plateau",
        ),
        _province_place(
            "ban-gioc",
            "Thác Bản Giốc",
            "north",
            "Cao Bằng",
            ["mountain", "culture"],
            "Thác nước biên giới nổi tiếng giữa núi rừng Đông Bắc, kết hợp hang Ngườm Ngao và làng đá Khuổi Ky.",
            ["Thác Bản Giốc", "Hang Ngườm Ngao", "Làng đá Khuổi Ky"],
            22.8555,
            106.7246,
            70000,
            1200000,
            4.8,
            94,
            image_hint="ban gioc waterfall",
        ),
        _province_place(
            "ba-be-lake",
            "Hồ Ba Bể",
            "north",
            "Bắc Kạn",
            ["mountain", "culture"],
            "Hồ nước ngọt tự nhiên giữa Vườn quốc gia Ba Bể, phù hợp du lịch sinh thái, chèo thuyền và homestay bản địa.",
            ["Hồ Ba Bể", "Động Puông", "Bản Pác Ngòi"],
            22.4004,
            105.6240,
            70000,
            1000000,
            4.6,
            88,
            image_hint="ba be lake national park",
        ),
        _province_place(
            "mau-son",
            "Mẫu Sơn",
            "north",
            "Lạng Sơn",
            ["mountain", "food", "culture"],
            "Vùng núi Đông Bắc có khí hậu mát, mùa đông có băng tuyết, kết hợp chợ Kỳ Lừa và ẩm thực xứ Lạng.",
            ["Đỉnh Mẫu Sơn", "Chợ Kỳ Lừa", "Ẩm thực xứ Lạng"],
            21.8540,
            106.9200,
            50000,
            900000,
            4.4,
            82,
            image_hint="mau son mountain",
        ),
        _province_place(
            "atks-dinh-hoa",
            "ATK Định Hóa",
            "north",
            "Thái Nguyên",
            ["history", "culture", "mountain"],
            "Khu di tích an toàn khu kháng chiến gắn với lịch sử cách mạng, gần các đồi chè và hồ Núi Cốc.",
            ["ATK Định Hóa", "Hồ Núi Cốc", "Đồi chè"],
            21.8896,
            105.6420,
            50000,
            850000,
            4.3,
            80,
            image_hint="thai nguyen tea hills",
        ),
        _province_place(
            "tay-yen-tu",
            "Tây Yên Tử",
            "north",
            "Bắc Giang",
            ["spiritual", "mountain", "culture"],
            "Không gian du lịch tâm linh phía Tây dãy Yên Tử, kết hợp rừng núi, chùa tháp và cáp treo.",
            ["Chùa Hạ", "Chùa Thượng", "Rừng Yên Tử"],
            21.2255,
            106.7130,
            150000,
            900000,
            4.5,
            84,
            image_hint="tay yen tu pagoda mountain",
        ),
        _province_place(
            "mai-chau",
            "Mai Châu",
            "north",
            "Hòa Bình",
            ["mountain", "culture", "food"],
            "Thung lũng yên bình với nhà sàn, bản Lác, ruộng lúa và văn hóa Thái đặc trưng.",
            ["Bản Lác", "Đèo Thung Khe", "Nhà sàn Thái"],
            20.6656,
            105.0759,
            60000,
            1000000,
            4.6,
            88,
            image_hint="mai chau valley rice fields",
        ),
        _province_place(
            "moc-chau",
            "Mộc Châu",
            "north",
            "Sơn La",
            ["mountain", "culture", "food"],
            "Cao nguyên chè, hoa mận, thác Dải Yếm và khí hậu trong lành phù hợp nghỉ dưỡng cuối tuần.",
            ["Đồi chè trái tim", "Thác Dải Yếm", "Rừng thông Bản Áng"],
            20.8299,
            104.6769,
            80000,
            1200000,
            4.7,
            90,
            image_hint="moc chau tea hills",
        ),
        _province_place(
            "dien-bien-phu",
            "Di tích Điện Biên Phủ",
            "north",
            "Điện Biên",
            ["history", "culture", "mountain"],
            "Quần thể di tích chiến thắng Điện Biên Phủ, kết hợp bảo tàng, đồi A1 và cánh đồng Mường Thanh.",
            ["Đồi A1", "Bảo tàng Chiến thắng", "Hầm Đờ Cát"],
            21.3860,
            103.0169,
            50000,
            1000000,
            4.6,
            89,
            image_hint="dien bien phu historical site",
        ),
        _province_place(
            "sin-ho",
            "Cao nguyên Sìn Hồ",
            "north",
            "Lai Châu",
            ["mountain", "culture"],
            "Cao nguyên mây phủ với chợ phiên, bản làng dân tộc và những cung đường núi Tây Bắc hoang sơ.",
            ["Chợ phiên Sìn Hồ", "Săn mây", "Bản làng vùng cao"],
            22.3667,
            103.2333,
            50000,
            1000000,
            4.3,
            82,
            image_hint="sin ho mountain clouds",
        ),
        _province_place(
            "mu-cang-chai",
            "Mù Cang Chải",
            "north",
            "Yên Bái",
            ["mountain", "culture"],
            "Danh thắng ruộng bậc thang nổi tiếng, đặc biệt đẹp vào mùa nước đổ và mùa lúa chín.",
            ["Ruộng bậc thang", "Đèo Khau Phạ", "Bản Lìm Mông"],
            21.8500,
            104.0833,
            80000,
            1300000,
            4.8,
            95,
            image_hint="mu cang chai rice terraces",
        ),
        _province_place(
            "sam-son",
            "Biển Sầm Sơn",
            "central",
            "Thanh Hóa",
            ["beach", "food"],
            "Bãi biển truyền thống miền Bắc Trung Bộ, kết hợp hải sản, Hòn Trống Mái và các khu nghỉ dưỡng ven biển.",
            ["Biển Sầm Sơn", "Hòn Trống Mái", "Hải sản"],
            19.7411,
            105.9022,
            0,
            1100000,
            4.3,
            80,
            transport_modes=["train", "bus", "car"],
            image_hint="sam son beach",
        ),
        _province_place(
            "cua-lo",
            "Biển Cửa Lò",
            "central",
            "Nghệ An",
            ["beach", "food", "culture"],
            "Bãi biển nổi tiếng Bắc Trung Bộ, thuận tiện kết hợp quê Bác, đảo Lan Châu và ẩm thực hải sản.",
            ["Biển Cửa Lò", "Đảo Lan Châu", "Quê Bác"],
            18.8167,
            105.7167,
            0,
            1100000,
            4.3,
            80,
            transport_modes=["plane", "train", "bus"],
            image_hint="cua lo beach",
        ),
        _province_place(
            "thien-cam",
            "Biển Thiên Cầm",
            "central",
            "Hà Tĩnh",
            ["beach", "food"],
            "Bãi biển yên bình với cát trắng, núi Thiên Cầm và hải sản địa phương.",
            ["Biển Thiên Cầm", "Núi Thiên Cầm", "Hải sản"],
            18.2711,
            106.0959,
            0,
            950000,
            4.2,
            76,
            transport_modes=["train", "bus", "car"],
            image_hint="thien cam beach",
        ),
        _province_place(
            "phong-nha",
            "Phong Nha - Kẻ Bàng",
            "central",
            "Quảng Bình",
            ["mountain", "history", "culture"],
            "Di sản thiên nhiên thế giới với hệ thống hang động kỳ vĩ, sông Son và các tuyến khám phá mạo hiểm.",
            ["Động Phong Nha", "Động Thiên Đường", "Sông Son"],
            17.5900,
            106.2830,
            250000,
            1500000,
            4.8,
            96,
            transport_modes=["plane", "train", "bus"],
            image_hint="phong nha cave river",
        ),
        _province_place(
            "vinh-moc",
            "Địa đạo Vịnh Mốc",
            "central",
            "Quảng Trị",
            ["history", "culture", "beach"],
            "Di tích địa đạo ven biển gắn với thời chiến, gần cầu Hiền Lương, sông Bến Hải và các điểm lịch sử DMZ.",
            ["Địa đạo Vịnh Mốc", "Cầu Hiền Lương", "Sông Bến Hải"],
            17.0739,
            107.1047,
            40000,
            850000,
            4.4,
            82,
            transport_modes=["train", "bus", "car"],
            image_hint="vinh moc tunnels",
        ),
        _province_place(
            "ly-son",
            "Đảo Lý Sơn",
            "central",
            "Quảng Ngãi",
            ["island", "beach", "culture"],
            "Đảo núi lửa ngoài khơi Quảng Ngãi nổi bật với biển xanh, cổng Tò Vò, ruộng tỏi và văn hóa biển đảo.",
            ["Cổng Tò Vò", "Hang Câu", "Ruộng tỏi"],
            15.3833,
            109.1167,
            150000,
            1400000,
            4.6,
            88,
            transport_modes=["train", "bus", "ship"],
            image_hint="ly son island volcanic coast",
        ),
        _province_place(
            "ky-co",
            "Kỳ Co - Eo Gió",
            "central",
            "Bình Định",
            ["beach", "food", "culture"],
            "Cụm điểm biển nổi tiếng của Quy Nhơn với nước xanh, vách đá, hải sản và trải nghiệm cano.",
            ["Kỳ Co", "Eo Gió", "Tháp Đôi"],
            13.8926,
            109.2870,
            170000,
            1400000,
            4.7,
            91,
            transport_modes=["plane", "train", "bus"],
            image_hint="ky co eo gio beach",
        ),
        _province_place(
            "ghenh-da-dia",
            "Gành Đá Đĩa",
            "central",
            "Phú Yên",
            ["beach", "culture"],
            "Danh thắng ven biển với các khối đá bazan xếp lớp, gần đầm Ô Loan và Bãi Xép.",
            ["Gành Đá Đĩa", "Đầm Ô Loan", "Bãi Xép"],
            13.3539,
            109.2930,
            40000,
            1000000,
            4.6,
            86,
            transport_modes=["plane", "train", "bus"],
            image_hint="ghenh da dia basalt coast",
        ),
        _province_place(
            "nha-trang",
            "Nha Trang",
            "central",
            "Khánh Hòa",
            ["beach", "island", "entertainment"],
            "Thành phố biển nổi tiếng với vịnh Nha Trang, đảo Hòn Mun, tháp Bà Ponagar và các khu vui chơi.",
            ["Vịnh Nha Trang", "Hòn Mun", "Tháp Bà Ponagar"],
            12.2388,
            109.1967,
            150000,
            1700000,
            4.7,
            93,
            transport_modes=["plane", "train", "bus"],
            image_hint="nha trang bay beach",
        ),
        _province_place(
            "ninh-chu",
            "Biển Ninh Chữ",
            "central",
            "Ninh Thuận",
            ["beach", "culture", "food"],
            "Bãi biển yên tĩnh gần vườn nho, tháp Chăm và cung đường ven biển Vĩnh Hy.",
            ["Biển Ninh Chữ", "Vịnh Vĩnh Hy", "Vườn nho"],
            11.5900,
            109.0300,
            50000,
            1000000,
            4.3,
            80,
            transport_modes=["train", "bus", "car"],
            image_hint="ninh chu beach vineyard",
        ),
        _province_place(
            "mui-ne",
            "Mũi Né",
            "central",
            "Bình Thuận",
            ["beach", "food", "entertainment"],
            "Thiên đường biển và đồi cát với các hoạt động thể thao biển, làng chài và cung đường ven biển.",
            ["Đồi cát bay", "Làng chài Mũi Né", "Suối Tiên"],
            10.9333,
            108.2833,
            50000,
            1300000,
            4.5,
            86,
            transport_modes=["train", "bus", "car"],
            image_hint="mui ne sand dunes beach",
        ),
        _province_place(
            "mang-den",
            "Măng Đen",
            "central",
            "Kon Tum",
            ["mountain", "culture"],
            "Thị trấn cao nguyên mát mẻ với rừng thông, hồ thác và văn hóa bản địa Tây Nguyên.",
            ["Rừng thông Măng Đen", "Hồ Đăk Ke", "Thác Pa Sỹ"],
            14.6042,
            108.2940,
            50000,
            1000000,
            4.5,
            84,
            transport_modes=["plane", "bus", "car"],
            image_hint="mang den pine forest",
        ),
        _province_place(
            "bien-ho-che",
            "Biển Hồ Chè",
            "central",
            "Gia Lai",
            ["mountain", "culture", "food"],
            "Không gian cao nguyên với đồi chè, Biển Hồ Pleiku, núi lửa Chư Đăng Ya và cà phê đặc sản.",
            ["Biển Hồ", "Đồi chè", "Chư Đăng Ya"],
            14.0635,
            108.0040,
            40000,
            950000,
            4.5,
            84,
            transport_modes=["plane", "bus", "car"],
            image_hint="pleiku tea lake volcano",
        ),
        _province_place(
            "buon-don",
            "Buôn Đôn",
            "central",
            "Đắk Lắk",
            ["culture", "mountain", "food"],
            "Vùng văn hóa Tây Nguyên nổi tiếng với nhà dài, voi, sông Sêrêpốk, cà phê và không gian cồng chiêng.",
            ["Buôn Đôn", "Thác Dray Nur", "Bảo tàng cà phê"],
            12.8792,
            107.7300,
            80000,
            1100000,
            4.5,
            85,
            transport_modes=["plane", "bus", "car"],
            image_hint="dak lak highland coffee waterfall",
        ),
        _province_place(
            "ta-dung",
            "Tà Đùng",
            "central",
            "Đắk Nông",
            ["mountain", "culture"],
            "Hồ Tà Đùng được ví như vịnh Hạ Long trên cao nguyên với nhiều đảo nhỏ và cảnh quan săn mây.",
            ["Hồ Tà Đùng", "Săn mây", "Cung đường cao nguyên"],
            11.8667,
            107.9833,
            50000,
            1000000,
            4.6,
            86,
            transport_modes=["bus", "car"],
            image_hint="ta dung lake highland",
        ),
        _province_place(
            "da-lat",
            "Đà Lạt",
            "central",
            "Lâm Đồng",
            ["mountain", "culture", "food"],
            "Thành phố cao nguyên với khí hậu mát, hồ Xuân Hương, rừng thông, nông trại và văn hóa cà phê.",
            ["Hồ Xuân Hương", "Thung lũng Tình Yêu", "Đồi chè Cầu Đất"],
            11.9404,
            108.4583,
            120000,
            1500000,
            4.8,
            94,
            transport_modes=["plane", "bus", "car"],
            image_hint="da lat pine forest lake",
        ),
        _province_place(
            "bu-gia-map",
            "Vườn quốc gia Bù Gia Mập",
            "south",
            "Bình Phước",
            ["mountain", "culture"],
            "Không gian rừng nguyên sinh Đông Nam Bộ phù hợp trekking, quan sát thiên nhiên và tìm hiểu văn hóa S'tiêng.",
            ["Rừng Bù Gia Mập", "Trekking", "Văn hóa S'tiêng"],
            12.2040,
            107.1880,
            80000,
            900000,
            4.2,
            76,
            image_hint="bu gia map national park",
        ),
        _province_place(
            "ba-den",
            "Núi Bà Đen",
            "south",
            "Tây Ninh",
            ["mountain", "spiritual", "culture"],
            "Nóc nhà Nam Bộ với cáp treo, chùa Bà và tầm nhìn toàn cảnh đồng bằng Đông Nam Bộ.",
            ["Núi Bà Đen", "Chùa Bà", "Cáp treo"],
            11.3717,
            106.1667,
            250000,
            1000000,
            4.6,
            89,
            image_hint="ba den mountain pagoda",
        ),
        _province_place(
            "dai-nam",
            "Khu du lịch Đại Nam",
            "south",
            "Bình Dương",
            ["entertainment", "spiritual", "culture"],
            "Tổ hợp vui chơi, đền thờ, biển nhân tạo và vườn thú, phù hợp gia đình gần TP. Hồ Chí Minh.",
            ["Đại Nam Văn Hiến", "Vườn thú", "Biển nhân tạo"],
            11.0450,
            106.6717,
            300000,
            1000000,
            4.2,
            78,
            image_hint="dai nam theme park",
        ),
        _province_place(
            "buulong",
            "Khu du lịch Bửu Long",
            "south",
            "Đồng Nai",
            ["entertainment", "culture"],
            "Không gian hồ nước, núi đá và vui chơi ngoài trời gần Biên Hòa, phù hợp chuyến đi ngắn trong ngày.",
            ["Hồ Long Ẩn", "Núi Bình Điện", "Khu vui chơi"],
            10.9616,
            106.7942,
            150000,
            850000,
            4.2,
            77,
            image_hint="buu long lake park",
        ),
        _province_place(
            "vung-tau",
            "Vũng Tàu",
            "south",
            "Bà Rịa - Vũng Tàu",
            ["beach", "food", "culture"],
            "Thành phố biển gần TP. Hồ Chí Minh với Bãi Sau, tượng Chúa Kitô, hải sản và các tuyến nghỉ dưỡng cuối tuần.",
            ["Bãi Sau", "Tượng Chúa Kitô", "Hải sản"],
            10.4114,
            107.1362,
            0,
            1200000,
            4.5,
            86,
            transport_modes=["bus", "car", "ship"],
            image_hint="vung tau beach lighthouse",
        ),
        _province_place(
            "tan-lap",
            "Làng nổi Tân Lập",
            "south",
            "Long An",
            ["culture", "food"],
            "Khu sinh thái rừng tràm với đường xuyên rừng, thuyền len lỏi kênh rạch và không gian miền Tây gần Sài Gòn.",
            ["Rừng tràm Tân Lập", "Thuyền kênh rạch", "Đài quan sát"],
            10.6830,
            105.9990,
            80000,
            800000,
            4.3,
            80,
            image_hint="tan lap floating village",
        ),
        _province_place(
            "cai-be",
            "Cái Bè",
            "south",
            "Tiền Giang",
            ["culture", "food"],
            "Điểm đến sông nước với cù lao, nhà cổ, vườn trái cây và trải nghiệm chợ nổi miền Tây.",
            ["Cù lao Tân Phong", "Nhà cổ", "Vườn trái cây"],
            10.3333,
            105.9500,
            70000,
            850000,
            4.3,
            80,
            image_hint="cai be mekong river",
        ),
        _province_place(
            "con-phung",
            "Cồn Phụng",
            "south",
            "Bến Tre",
            ["culture", "food"],
            "Cồn du lịch trên sông Tiền với vườn dừa, kẹo dừa, đờn ca tài tử và trải nghiệm xuồng ba lá.",
            ["Vườn dừa", "Kẹo dừa", "Xuồng ba lá"],
            10.3040,
            106.3670,
            90000,
            850000,
            4.3,
            79,
            image_hint="ben tre coconut island",
        ),
        _province_place(
            "ao-ba-om",
            "Ao Bà Om",
            "south",
            "Trà Vinh",
            ["spiritual", "culture", "food"],
            "Không gian văn hóa Khmer với ao Bà Om, chùa cổ và ẩm thực đặc trưng Nam Bộ.",
            ["Ao Bà Om", "Chùa Âng", "Văn hóa Khmer"],
            9.9342,
            106.3457,
            30000,
            750000,
            4.2,
            78,
            image_hint="tra vinh khmer pagoda pond",
        ),
        _province_place(
            "an-binh",
            "Cù lao An Bình",
            "south",
            "Vĩnh Long",
            ["culture", "food"],
            "Cù lao sông nước với homestay miệt vườn, trái cây, kênh rạch và trải nghiệm đời sống miền Tây.",
            ["Homestay miệt vườn", "Vườn trái cây", "Kênh rạch"],
            10.2536,
            105.9722,
            60000,
            800000,
            4.3,
            79,
            image_hint="vinh long orchard island",
        ),
        _province_place(
            "tram-chim",
            "Vườn quốc gia Tràm Chim",
            "south",
            "Đồng Tháp",
            ["culture", "food"],
            "Vùng đất ngập nước tiêu biểu Đồng Tháp Mười, nổi bật mùa sen và quan sát chim nước.",
            ["Tràm Chim", "Đồng sen", "Chim nước"],
            10.7280,
            105.5150,
            100000,
            850000,
            4.4,
            82,
            image_hint="tram chim national park lotus",
        ),
        _province_place(
            "tra-su",
            "Rừng tràm Trà Sư",
            "south",
            "An Giang",
            ["spiritual", "culture", "food"],
            "Rừng tràm ngập nước nổi tiếng với thảm bèo xanh, chim nước, gần Núi Sam và các điểm tâm linh Châu Đốc.",
            ["Rừng tràm Trà Sư", "Miếu Bà Chúa Xứ", "Núi Sam"],
            10.5862,
            105.0809,
            150000,
            1000000,
            4.6,
            88,
            image_hint="tra su melaleuca forest",
        ),
        _province_place(
            "lung-ngoc-hoang",
            "Khu bảo tồn Lung Ngọc Hoàng",
            "south",
            "Hậu Giang",
            ["culture", "food"],
            "Vùng sinh thái đất ngập nước với rừng tràm, chim nước và trải nghiệm thiên nhiên miền Tây.",
            ["Lung Ngọc Hoàng", "Rừng tràm", "Chim nước"],
            9.7600,
            105.6200,
            80000,
            750000,
            4.2,
            76,
            image_hint="lung ngoc hoang wetland",
        ),
        _province_place(
            "nga-nam",
            "Chợ nổi Ngã Năm",
            "south",
            "Sóc Trăng",
            ["culture", "food"],
            "Chợ nổi giao thương đặc trưng miền Tây, kết hợp văn hóa Khmer và ẩm thực Sóc Trăng.",
            ["Chợ nổi Ngã Năm", "Chùa Dơi", "Bánh pía"],
            9.5580,
            105.5940,
            50000,
            750000,
            4.3,
            80,
            image_hint="nga nam floating market",
        ),
        _province_place(
            "bac-lieu-wind-farm",
            "Cánh đồng điện gió Bạc Liêu",
            "south",
            "Bạc Liêu",
            ["culture", "food"],
            "Biểu tượng ven biển Bạc Liêu với tuabin gió, nhà Công tử Bạc Liêu và không gian đờn ca tài tử.",
            ["Điện gió Bạc Liêu", "Nhà Công tử Bạc Liêu", "Đờn ca tài tử"],
            9.2386,
            105.7642,
            40000,
            800000,
            4.4,
            82,
            image_hint="bac lieu wind farm",
        ),
        _province_place(
            "dat-mui",
            "Đất Mũi Cà Mau",
            "south",
            "Cà Mau",
            ["culture", "food", "beach"],
            "Điểm cực Nam Tổ quốc với rừng ngập mặn, cột mốc tọa độ và trải nghiệm sinh thái cuối đất nước.",
            ["Mũi Cà Mau", "Rừng ngập mặn", "Cột mốc tọa độ"],
            8.6211,
            104.7246,
            100000,
            1100000,
            4.6,
            90,
            transport_modes=["plane", "bus", "car"],
            image_hint="dat mui ca mau mangrove",
        ),
    ]
)

PLACES[:] = [
    place.model_copy(update={"province": normalize_province_name(place.province)})
    for place in PLACES
]


TICKET_OFFERS: list[TicketOffer] = [
    TicketOffer(
        provider="Vietnam Airlines",
        vehicle_type="plane",
        origin="Hà Nội",
        destination="Thành phố Hồ Chí Minh",
        departure="07:30",
        departure_date="2026-06-15",
        arrival="09:40",
        duration="2h 10m",
        seat_class="Economy Flex",
        available_seats=9,
        operator_note="Đã bao gồm 23kg hành lý ký gửi.",
        price=1890000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vna-han-sgn-0730",
    ),
    TicketOffer(
        provider="Vietjet Air",
        vehicle_type="plane",
        origin="Hà Nội",
        destination="Thành phố Hồ Chí Minh",
        departure="13:20",
        departure_date="2026-06-15",
        arrival="15:35",
        duration="2h 15m",
        seat_class="Deluxe",
        available_seats=14,
        operator_note="Ưu đãi thêm 7kg hành lý xách tay.",
        price=1450000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vj-han-sgn-1320",
    ),
    TicketOffer(
        provider="Bamboo Airways",
        vehicle_type="plane",
        origin="Hà Nội",
        destination="Thành phố Hồ Chí Minh",
        departure="18:05",
        departure_date="2026-06-15",
        arrival="20:20",
        duration="2h 15m",
        seat_class="Economy Smart",
        available_seats=6,
        operator_note="Miễn phí đổi giờ trong 24 giờ đầu.",
        price=1620000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/qh-han-sgn-1805",
    ),
    TicketOffer(
        provider="Vietnam Airlines",
        vehicle_type="plane",
        origin="Thành phố Hồ Chí Minh",
        destination="Hà Nội",
        departure="06:45",
        departure_date="2026-06-16",
        arrival="08:55",
        duration="2h 10m",
        seat_class="Economy Classic",
        available_seats=11,
        operator_note="Làm thủ tục trước 40 phút.",
        price=1840000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vna-sgn-han-0645",
    ),
    TicketOffer(
        provider="Vietjet Air",
        vehicle_type="plane",
        origin="Thành phố Hồ Chí Minh",
        destination="Hà Nội",
        departure="15:10",
        departure_date="2026-06-16",
        arrival="17:20",
        duration="2h 10m",
        seat_class="SkyBoss Eco",
        available_seats=10,
        operator_note="Có suất ăn nhẹ trong gói giá.",
        price=1530000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vj-sgn-han-1510",
    ),
    TicketOffer(
        provider="Bamboo Airways",
        vehicle_type="plane",
        origin="Thành phố Hồ Chí Minh",
        destination="Hà Nội",
        departure="20:20",
        departure_date="2026-06-16",
        arrival="22:35",
        duration="2h 15m",
        seat_class="Business Saver",
        available_seats=4,
        operator_note="Phù hợp khách công tác, hoàn đổi linh hoạt.",
        price=2790000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/qh-sgn-han-2020",
    ),
    TicketOffer(
        provider="Vietnam Airlines",
        vehicle_type="plane",
        origin="Hà Nội",
        destination="Phú Quốc",
        departure="06:30",
        departure_date="2026-06-17",
        arrival="08:40",
        duration="2h 10m",
        seat_class="Economy Flex",
        available_seats=8,
        operator_note="Bay thẳng, ưu tiên check-in trực tuyến.",
        price=2100000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vna-han-pqc-0630",
    ),
    TicketOffer(
        provider="Vietjet Air",
        vehicle_type="plane",
        origin="Hà Nội",
        destination="Phú Quốc",
        departure="11:15",
        departure_date="2026-06-17",
        arrival="13:25",
        duration="2h 10m",
        seat_class="Eco",
        available_seats=16,
        operator_note="Giá chưa gồm hành lý ký gửi.",
        price=1680000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vj-han-pqc-1115",
    ),
    TicketOffer(
        provider="Vietnam Airlines",
        vehicle_type="plane",
        origin="Thành phố Hồ Chí Minh",
        destination="Phú Quốc",
        departure="07:10",
        departure_date="2026-06-18",
        arrival="08:15",
        duration="1h 05m",
        seat_class="Economy Classic",
        available_seats=12,
        operator_note="Khởi hành từ nhà ga quốc nội T3.",
        price=1550000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vna-sgn-pqc-0710",
    ),
    TicketOffer(
        provider="Bamboo Airways",
        vehicle_type="plane",
        origin="Thành phố Hồ Chí Minh",
        destination="Phú Quốc",
        departure="17:50",
        departure_date="2026-06-18",
        arrival="18:55",
        duration="1h 05m",
        seat_class="Economy Smart",
        available_seats=9,
        operator_note="Thích hợp cho lịch check-in resort buổi tối.",
        price=1490000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/qh-sgn-pqc-1750",
    ),
    TicketOffer(
        provider="Vietnam Airlines",
        vehicle_type="plane",
        origin="Hà Nội",
        destination="Đà Nẵng",
        departure="08:15",
        departure_date="2026-06-15",
        arrival="09:35",
        duration="1h 20m",
        seat_class="Economy Classic",
        available_seats=15,
        operator_note="Phù hợp nối chuyến đi Hội An hoặc Bà Nà Hills.",
        price=1190000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vna-han-dad-0815",
    ),
    TicketOffer(
        provider="Vietjet Air",
        vehicle_type="plane",
        origin="Hà Nội",
        destination="Đà Nẵng",
        departure="21:05",
        departure_date="2026-06-15",
        arrival="22:25",
        duration="1h 20m",
        seat_class="Deluxe",
        available_seats=13,
        operator_note="Khung giờ muộn, thích hợp nghỉ đêm tại Đà Nẵng.",
        price=1050000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vj-han-dad-2105",
    ),
    TicketOffer(
        provider="Đường sắt Việt Nam",
        vehicle_type="train",
        origin="Đà Nẵng",
        destination="Huế",
        departure="08:00",
        departure_date="2026-06-16",
        arrival="10:52",
        duration="2h 52m",
        seat_class="Ghế mềm điều hòa",
        available_seats=28,
        operator_note="Cung đường đèo Hải Vân ngắm biển đẹp.",
        price=420000,
        booking_url="https://booking.demo.touchvietnam.vn/trains/se-dad-hue-0800",
    ),
    TicketOffer(
        provider="Hue Heritage Rail",
        vehicle_type="train",
        origin="Đà Nẵng",
        destination="Huế",
        departure="14:20",
        departure_date="2026-06-16",
        arrival="17:05",
        duration="2h 45m",
        seat_class="Toa du lịch",
        available_seats=18,
        operator_note="Có phục vụ đồ uống trên toa.",
        price=560000,
        booking_url="https://booking.demo.touchvietnam.vn/trains/hhr-dad-hue-1420",
    ),
    TicketOffer(
        provider="Hoi An Express",
        vehicle_type="bus",
        origin="Đà Nẵng",
        destination="Hội An",
        departure="10:30",
        departure_date="2026-06-15",
        arrival="11:20",
        duration="50m",
        seat_class="Limousine 9 chỗ",
        available_seats=5,
        operator_note="Đón tại sân bay Đà Nẵng theo yêu cầu.",
        price=180000,
        booking_url="https://booking.demo.touchvietnam.vn/bus/dad-hoian-1030",
    ),
    TicketOffer(
        provider="Barri Ann Travel",
        vehicle_type="bus",
        origin="Đà Nẵng",
        destination="Hội An",
        departure="16:00",
        departure_date="2026-06-15",
        arrival="16:50",
        duration="50m",
        seat_class="Shuttle bus",
        available_seats=11,
        operator_note="Xe trung chuyển phố cổ, phù hợp khách gia đình.",
        price=140000,
        booking_url="https://booking.demo.touchvietnam.vn/bus/dad-hoian-1600",
    ),
    TicketOffer(
        provider="InterBus Lines",
        vehicle_type="bus",
        origin="Hà Nội",
        destination="Sa Pa",
        departure="22:00",
        departure_date="2026-06-15",
        arrival="04:50",
        duration="6h 50m",
        seat_class="Cabin đôi",
        available_seats=7,
        operator_note="Có chăn, nước suối và điểm đón trung tâm Hà Nội.",
        price=350000,
        booking_url="https://booking.demo.touchvietnam.vn/bus/han-sapa-2200",
    ),
    TicketOffer(
        provider="Sa Pa Cabin",
        vehicle_type="bus",
        origin="Hà Nội",
        destination="Sa Pa",
        departure="21:30",
        departure_date="2026-06-15",
        arrival="04:20",
        duration="6h 50m",
        seat_class="VIP Cabin",
        available_seats=4,
        operator_note="Xe giường phòng riêng, phù hợp nhóm đôi.",
        price=420000,
        booking_url="https://booking.demo.touchvietnam.vn/bus/han-sapa-2130",
    ),
    TicketOffer(
        provider="Đường sắt Việt Nam",
        vehicle_type="train",
        origin="Hà Nội",
        destination="Sa Pa",
        departure="22:00",
        departure_date="2026-06-15",
        arrival="06:05",
        duration="8h 05m",
        seat_class="Giường nằm khoang 4",
        available_seats=12,
        operator_note="Xuống ga Lào Cai và tiếp tục shuttle lên Sa Pa.",
        price=780000,
        booking_url="https://booking.demo.touchvietnam.vn/trains/han-laocai-2200",
    ),
    TicketOffer(
        provider="Quang Ninh Limousine",
        vehicle_type="bus",
        origin="Hà Nội",
        destination="Hạ Long",
        departure="06:45",
        departure_date="2026-06-16",
        arrival="09:20",
        duration="2h 35m",
        seat_class="Limousine 11 chỗ",
        available_seats=6,
        operator_note="Trả khách gần bến du thuyền Tuần Châu.",
        price=280000,
        booking_url="https://booking.demo.touchvietnam.vn/bus/han-halong-0645",
    ),
    TicketOffer(
        provider="Luxury Van",
        vehicle_type="bus",
        origin="Hà Nội",
        destination="Hạ Long",
        departure="13:30",
        departure_date="2026-06-16",
        arrival="16:05",
        duration="2h 35m",
        seat_class="Business Van",
        available_seats=8,
        operator_note="Có hỗ trợ đón khách tại khu phố cổ.",
        price=320000,
        booking_url="https://booking.demo.touchvietnam.vn/bus/han-halong-1330",
    ),
    TicketOffer(
        provider="Ninh Bình Limousine",
        vehicle_type="bus",
        origin="Hà Nội",
        destination="Tràng An",
        departure="07:15",
        departure_date="2026-06-16",
        arrival="09:05",
        duration="1h 50m",
        seat_class="Limousine VIP",
        available_seats=9,
        operator_note="Đưa thẳng đến bến thuyền Tràng An.",
        price=220000,
        booking_url="https://booking.demo.touchvietnam.vn/bus/han-trangan-0715",
    ),
    TicketOffer(
        provider="Vietnam Airlines",
        vehicle_type="plane",
        origin="Thành phố Hồ Chí Minh",
        destination="Cần Thơ",
        departure="08:10",
        departure_date="2026-06-17",
        arrival="08:55",
        duration="45m",
        seat_class="Economy",
        available_seats=21,
        operator_note="Phù hợp chuyến công tác hoặc nghỉ ngắn ngày miền Tây.",
        price=980000,
        booking_url="https://booking.demo.touchvietnam.vn/flights/vna-sgn-vca-0810",
    ),
    TicketOffer(
        provider="Phương Trang",
        vehicle_type="bus",
        origin="Thành phố Hồ Chí Minh",
        destination="Cần Thơ",
        departure="09:00",
        departure_date="2026-06-17",
        arrival="12:30",
        duration="3h 30m",
        seat_class="Giường nằm",
        available_seats=17,
        operator_note="Bến xe trung tâm, có trung chuyển nội thành.",
        price=165000,
        booking_url="https://booking.demo.touchvietnam.vn/bus/sgn-cantho-0900",
    ),
    TicketOffer(
        provider="Sun World Ba Na Hills",
        vehicle_type="entertainment",
        origin="Đà Nẵng",
        destination="Bà Nà Hills",
        departure="08:00",
        departure_date="2026-06-15",
        arrival="17:00",
        duration="1 ngày",
        seat_class="Combo cáp treo + tham quan",
        available_seats=120,
        operator_note="Vé điện tử vào cổng, chưa gồm buffet trưa.",
        price=900000,
        booking_url="https://booking.demo.touchvietnam.vn/attraction/bana-combo",
    ),
    TicketOffer(
        provider="Sun World Ha Long",
        vehicle_type="entertainment",
        origin="Hạ Long",
        destination="Hạ Long",
        departure="09:00",
        departure_date="2026-06-16",
        arrival="18:00",
        duration="1 ngày",
        seat_class="Combo Dragon Park",
        available_seats=85,
        operator_note="Phù hợp khách gia đình và nhóm bạn trẻ.",
        price=650000,
        booking_url="https://booking.demo.touchvietnam.vn/attraction/halong-dragonpark",
    ),
    TicketOffer(
        provider="VinWonders Phú Quốc",
        vehicle_type="entertainment",
        origin="Phú Quốc",
        destination="Phú Quốc",
        departure="09:00",
        departure_date="2026-06-18",
        arrival="19:30",
        duration="1 ngày",
        seat_class="All-in-one pass",
        available_seats=140,
        operator_note="Có thể kết hợp safari theo gói combo nâng cấp.",
        price=950000,
        booking_url="https://booking.demo.touchvietnam.vn/attraction/vinwonders-pq",
    ),
    TicketOffer(
        provider="Hoi An Memories",
        vehicle_type="entertainment",
        origin="Hội An",
        destination="Hội An",
        departure="20:00",
        departure_date="2026-06-15",
        arrival="21:10",
        duration="1h 10m",
        seat_class="Khán đài Eco",
        available_seats=38,
        operator_note="Thích hợp lịch trình buổi tối tại phố cổ.",
        price=620000,
        booking_url="https://booking.demo.touchvietnam.vn/attraction/hoian-memories",
    ),
]


PLACE_VIEWS: dict[str, int] = {
    "ha-long-bay": 18420,
    "sapa": 16310,
    "trang-an": 14280,
    "hue-imperial-city": 13640,
    "hoi-an": 22190,
    "ba-na-hills": 15110,
    "phu-quoc": 24870,
    "can-tho": 10940,
    "ho-chi-minh-city": 20760,
}


SUPPORTED_LANGUAGES = [
    {"code": "vi", "label": "Tiếng Việt"},
    {"code": "en", "label": "English"},
    {"code": "ko", "label": "Korean"},
]


AR_LANDMARKS = [
    {
        "name": "Hoàng thành Thăng Long",
        "province": "Hà Nội",
        "note": "Quét bằng camera để hiển thị thông tin lịch sử và mô hình 3D của công trình.",
    },
    {
        "name": "Đại Nội Huế",
        "province": "Huế",
        "note": "AR phục dựng một số không gian cung đình và giải thích nghệ thuật kiến trúc.",
    },
    {
        "name": "Địa đạo Củ Chi",
        "province": "Thành phố Hồ Chí Minh",
        "note": "Hiển thị dòng thời gian trận chiến, sa bàn và thông tin tương tác.",
    },
]


OFFLINE_MAP_PACKS = [
    {
        "region": "north",
        "name": "Tây Bắc Safe Travel Pack",
        "coverage": "Sa Pa, Y Tý, Bắc Hà và các khu vực sóng yếu miền núi.",
    },
    {
        "region": "central",
        "name": "Central Heritage Pack",
        "coverage": "Huế, Hội An, Đà Nẵng và các điểm di sản ven biển miền Trung.",
    },
    {
        "region": "south",
        "name": "Island and Mekong Pack",
        "coverage": "Phú Quốc, Hà Tiên, Cần Thơ và các cung đường sông nước miền Tây.",
    },
]
